version: '3'

services:
  flask_app:
    build: .
    ports:
      - "5000:5000"  # Ensure Flask is exposed on port 5000
    networks:
      - mynetwork
  db:
    image: postgres:13
    container_name: my_postgres_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

  pgadmin:
    image: dpage/pgadmin4
    container_name: my_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "80:80"
    networks:
      - mynetwork
    depends_on:
      - db

volumes:
  postgres_data:

networks:
  mynetwork:
    driver: bridge
